### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tofi86** [AlexJitianu/oXygen-XML-editor-xspec-support#2]
Hi Alex,

unfortunately I cannot get the plugin to work with this XSpec file: https://github.com/paginagmbh/xLib/blob/master/test/xslt-unit-tests.xspec

The plugin was installed correctly, the plugin button is available but nothing happens when I click it while the XSpec file is opened.

Any idea?

Cheers,
Tobias

**Comment by AlexJitianu** [comment]
Hi Tobias,

The plugin requires a special XSpec Oxygen framework and it contributes this plugin through the means of the "additional frameworks locations". This framework contributes a scenario named "XSpec Report" and I use Oxygen's API to execute it: `ro.sync.exml.workspace.api.editor.transformation.TransformationScenarioInvoker.runTransformationScenarios(String[], TransformationFeedback)`
I chose to do it like this because it was the fastest implementation option. In theory the plugin could start an ANT process directly instead but additional code would have to be written. I am open to suggestions.

If an exception appears in the console with the message "Transformation scenario not found: XSpec Report" then here is what you can do:
1. go to **Options->Preferences...** and select the **Locations** page.
2. check if the page is saved as "Global". If it isn't, switch it to Global
3. check if a long location with "xspec.support" in the path appears.

After my user meetup presentation, at some point, I realized that I didn't handle a situation. I made some changes and committed a new build on Feb 10.  It wouldn't hurt to update to that version as well.

As many are using project options, this situation could happen to others too... 

Kind regards,
Alex

**Comment by tofi86** [comment]
Oh, okay, indeed that was the problem! I am using a lot of project files which contribute external framework directories through the project options, so this would never work...

Can you clarify this in the Readme? Probably after merging my Readme Install docs #1?

Probably we should wait for oXygen 19 with the possibility of bundling frameworks with plugins... ;-)

**Comment by AlexJitianu** [comment]
Version 19.0 wouldn't help much... The project is a layer that applies on top of all other options so even frameworks bundled with a plugin will be overridden. I'll have to talk with my colleagues and see what we can do about it.

**Comment by tofi86** [comment]
> Version 19.0 wouldn't help much... The project is a layer that applies on top of all other options so even frameworks bundled with a plugin will be overridden. I'll have to talk with my colleagues and see what we can do about it.

Damn! ;-)

Well, I think this has also been on the list of projects/frameworks/plugins issues in my long mail from last year...

**Comment by AlexJitianu** [comment]
Ups, I talked without thinking  it through... In version 19 everything will be fine. Frameworks installed as add-ons or those contributed by plugins will always be loaded. As a workaround for v18 I could pack the framework as an add-on and you'll have a chance to install them both.
